---
- name: Config NAGIOS4 with plugins
  hosts: IaaC:Monitoring:WEB-Servers
  user: idenisick
  gather_facts: yes
  become: yes

  tasks:
    - name: Configure ntp_client using role
      import_role:
        name: ntp_client
