- name: install zabbix official rpm key 
  rpm_key:
    state: present
    key: https://repo.zabbix.com/zabbix-official-repo.key
  become: yes
  tags:
    - rpm_key  
- zypper:
    name: 'https://repo.zabbix.com/zabbix/5.4/sles/15/x86_64/zabbix-release-5.4-1.sles15.noarch.rpm'
    state: present
- name: Install the Zabbix Agent 2
  zypper:
    name: zabbix-agent2
    state: latest