- name: install zabbix official rpm key 
  rpm_key:
    state: present
    key: https://repo.zabbix.com/zabbix-official-repo.key
  become: yes
  tags:
    - rpm_key         
- name: install the zabbix 5.4 rpm from a remote repo
  dnf:
    name: 'https://repo.zabbix.com/zabbix/5.4/rhel/8/x86_64/zabbix-release-5.4-1.el8.noarch.rpm'
    state: latest
  become: yes
  tags:
    - install_zabbix_repo  
- name: install the 5.4 version of zabbix 
  dnf:
    name: "{{ zabbix_packages }}"
    state: latest  
  become: yes
  tags:
    - zabbix_packages       
- name: firewalld open http traffic
  firewalld:
    service: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  with_items:
    - http
    - https
  notify: restart nginx
  notify: restart zabbix_server
  notify: restart zabbix_agent2
  notify: restart restart php_fpm
  notify: restart firewalld